server:
  servlet:
    context-path: /quartz-manager
    session.timeout : 28800
  port: 8080

app:
  name: quartz-manager
  
spring:
  thymeleaf: 
    cache: false
    mode: LEGACYHTML5

quartz:
  enabled: true

job: 
  frequency: 4000
  repeatCount: 19

logging:
  level:
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    it.fabioformosa: DEBUG
    
quartz-manager:
  security:
    login-model:
      form-login-enabled: true
      userpwd-filter-enabled : false
    jwt:
      enabled: true
      secret: "bibidibobidiboo"
      expiration-in-sec: 28800  # 8 hours
      header: "Authorization"
      cookie: AUTH-TOKEN
      header-strategy:
        enabled: false
        header: "Authorization"
      cookie-strategy:
        enabled: true
        cookie: AUTH-TOKEN
  jobClass: it.fabioformosa.quartzmanager.jobs.myjobs.SampleJob
  accounts:
    in-memory:
      enabled: true
      users:
        - name: admin
          password: admin
          roles:
            - ADMIN      
