server:
  servlet:
    context-path: /
    session.timeout : 28800
  port: 8080

app:
  name: quartz-manager
  
spring:
  thymeleaf: 
    cache: false
    mode: LEGACYHTML5
  jpa.open-in-view: false
#  liquibase:
#    change-log: "classpath:db/liquibase-changelog-master.xml"
#    contexts: default
#    user: quartzmanager
#    password: quartzmanager
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/quartzmanager"
#    username: quartzmanager
#    password: quartzmanager

#  quartz:
#    job-store-type: jdbc
#    initialize-schema: never
#    properties:
#      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      
#     org.quartz.jobStore.isClustered: true
#     org.quartz.scheduler.instanceId=AUTO

quartz:
  enabled: true

job: 
  frequency: 4000
  repeatCount: 19

logging:
  level:
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    it.fabioformosa: DEBUG
    org.quartz: DEBUG
    
quartz-manager:
  security:
    login-model:
      form-login-enabled: true
      userpwd-filter-enabled : false
    jwt:
      enabled: true
      secret: "bibidibobidiboo"
      expiration-in-sec: 28800  # 8 hours
      header-strategy:
        enabled: false
        header: "Authorization"
      cookie-strategy:
        enabled: true
        cookie: AUTH-TOKEN
  jobClass: it.fabioformosa.quartzmanager.jobs.myjobs.SampleJob
  accounts:
    in-memory:
      enabled: true
      users:
        - name: admin
          password: admin
          roles:
            - ADMIN      
