server:
  servlet:
    context-path: /
    session.timeout : 28800
  port: 8080

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa.open-in-view: false

quartz:
  enabled: true

job:
  frequency: 4000
  repeatCount: 19

logging:
  level:
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    it.fabioformosa: DEBUG
    org.quartz: INFO

quartz-manager:
  trigger:
    name: "sampletrigger"
  persistence:
    quartz:
      datasource:
        url: "jdbc:postgresql://localhost:5432/quartzmanager"
        user: "quartzmanager"
        password: "quartzmanager"
  security:
    login-model:
      form-login-enabled: true
      userpwd-filter-enabled : false
    jwt:
      enabled: true
      secret: "bibidibobidiboo"
      expiration-in-sec: 28800  # 8 hours
      header-strategy:
        enabled: false
        header: "Authorization"
      cookie-strategy:
        enabled: true
        cookie: AUTH-TOKEN
  jobClassPackages: it.fabioformosa.quartzmanager.jobs
  accounts:
    in-memory:
      enabled: true
      users:
        - name: admin
          password: admin
          roles:
            - ADMIN
