server:
  servlet:
    context-path: /quartz-manager
    session.timeout : 28800
  port: 8080

app:
  name: quartz-manager
  
spring:
  thymeleaf: 
    cache: false
    mode: LEGACYHTML5

quartz:
  enabled: true

job: 
  frequency: 4000
  repeatCount: 19

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: WARN
    it.fabioformosa: INFO
    
quartz-manager:
  jobClass: it.fabioformosa.quartzmanager.jobs.myjobs.SampleJob
  account:
    user: admin
    pwd: admin
      